export enum TaskStatus {
  TO_DO = "TO_DO",
  IN_PROGRESS = "IN_PROGRESS",
  BLOCKED = "BLOCKED",
  IN_REVIEW = "IN_REVIEW",
  READY_FOR_QA = "READY_FOR_QA",
  REOPENED = "REOPENED",
  READY_FOR_PRODUCTION = "READY_FOR_PRODUCTION",
  DONE = "DONE",
}
