import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import DashboardLayout from "@/components/layout/DashboardLayout";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        {/* <SidebarLg />

        <div className="lg:ml-64 min-h-screen flex flex-col">
          <Topbar />

          <main className="flex-1 p-4 lg:p-8 overflow-y-auto">{children}</main>
        </div> */}
        <DashboardLayout>{children}</DashboardLayout>
      </body>
    </html>
  );
}
